"""initial

Revision ID: 8f8537c2c4f7
Revises: 
Create Date: 2026-05-10 14:19:11.804730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8537c2c4f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('quest', 'streak', 'level', 'social', 'trade', 'sanctum', name='badge_category_enum'), nullable=False),
    sa.Column('icon_symbol', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_key', name='uq_badge_key')
    )
    op.create_table('level_titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_number', name='uq_level_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_hint', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('total_points', sa.BigInteger(), nullable=False),
    sa.Column('total_xp', sa.BigInteger(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('weekly_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily_streak_date', sa.DateTime(), nullable=True),
    sa.Column('last_weekly_streak_date', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("player_name ~ '^[a-zA-Z0-9_]{3,20}$'", name='chk_player_name'),
    sa.CheckConstraint('current_level >= 1', name='chk_level'),
    sa.CheckConstraint('total_points >= 0', name='chk_points_gte0'),
    sa.CheckConstraint('total_xp >= 0', name='chk_xp_gte0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('player_name', name='uq_player_name')
    )
    op.create_table('daily_streak_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('streak_date', sa.Date(), nullable=False),
    sa.Column('streak_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'streak_date', name='uq_daily_streak')
    )
    op.create_table('daily_trade_caps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_date', name='uq_daily_trade_cap')
    )
    op.create_table('guilds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sigil_code', sa.String(length=20), nullable=False),
    sa.Column('guild_master_id', sa.UUID(), nullable=False),
    sa.Column('max_points_per_quest', sa.Integer(), nullable=False),
    sa.Column('max_xp_per_quest', sa.Integer(), nullable=False),
    sa.Column('is_dissolved', sa.Boolean(), nullable=False),
    sa.Column('dissolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_points_per_quest > 0', name='chk_points_cap'),
    sa.CheckConstraint('max_xp_per_quest > 0', name='chk_xp_cap'),
    sa.ForeignKeyConstraint(['guild_master_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigil_code', name='uq_sigil_code')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('proposals_voting', 'deadline_reminders', 'level_badge', 'trade_alerts', 'group_progress', 'guild_membership', name='notification_category_enum'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_notif_setting')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('proposals_voting', 'deadline_reminders', 'level_badge', 'trade_alerts', 'group_progress', 'guild_membership', name='notification_category_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_reset_token')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('transaction_type', sa.Enum('quest_reward', 'competition_reward', 'trade_sent', 'trade_received', 'trade_tax', name='transaction_type_enum'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanctums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_sanctum_user')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_token_hash')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_table('weekly_streak_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('streak_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_streak')
    )
    op.create_table('xp_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_archives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('guild_name', sa.String(length=100), nullable=False),
    sa.Column('archive_data', sa.Text(), nullable=False),
    sa.Column('dissolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_guild_member')
    )
    op.create_table('quest_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=True),
    sa.Column('sanctum_id', sa.UUID(), nullable=True),
    sa.Column('proposed_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quest_type', sa.Enum('daily', 'weekly', 'occasional', 'competition', 'group', name='quest_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('fitness', 'study', 'creative', 'social', 'wellness', 'other', name='quest_category_enum'), nullable=False),
    sa.Column('category_custom_label', sa.String(length=30), nullable=True),
    sa.Column('point_worth', sa.Integer(), nullable=False),
    sa.Column('xp_worth', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winner_point_reward', sa.Integer(), nullable=True),
    sa.Column('runner_up_point_reward', sa.Integer(), nullable=True),
    sa.Column('has_collective_deadline', sa.Boolean(), nullable=False),
    sa.Column('collective_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'upcoming', 'completed', 'cancelled', 'archived', name='quest_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sanctum_id'], ['sanctums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasonal_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('season_month', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guild_id', 'season_year', 'season_month', name='uq_seasonal_points')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('amount_sent', sa.Integer(), nullable=False),
    sa.Column('amount_received', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='trade_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addon_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_template_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('point_worth', sa.Integer(), nullable=False),
    sa.Column('xp_worth', sa.Integer(), nullable=False),
    sa.Column('addon_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_template_id'], ['quest_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'upcoming', 'completed', 'cancelled', 'archived', name='quest_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['quest_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('proposed_by', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.Enum('create', 'edit', 'delete', name='proposal_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='proposal_status_enum'), nullable=False),
    sa.Column('proposed_data', sa.Text(), nullable=False),
    sa.Column('suggest_changes_notes', sa.Text(), nullable=True),
    sa.Column('voting_closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['quest_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('side_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_template_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('point_worth', sa.Integer(), nullable=False),
    sa.Column('xp_worth', sa.Integer(), nullable=False),
    sa.Column('unlock_hour_offset', sa.Integer(), nullable=False),
    sa.Column('unlocks_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_template_id'], ['quest_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addon_quest_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('addon_quest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['addon_quest_id'], ['addon_quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addon_quest_id', 'user_id', name='uq_aq_completion')
    )
    op.create_table('competition_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('winner_vote', sa.UUID(), nullable=True),
    sa.Column('runner_up_vote', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['quest_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_up_vote'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_vote'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'voter_id', name='uq_competition_vote')
    )
    op.create_table('proposal_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Enum('accept', 'decline', 'suggest_changes', name='vote_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['quest_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'user_id', name='uq_proposal_vote')
    )
    op.create_table('quest_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'done', 'missed', name='completion_status_enum'), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_multiplier_applied', sa.Float(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pin_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['quest_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'user_id', name='uq_completion')
    )
    op.create_table('side_quest_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('side_quest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['side_quest_id'], ['side_quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('side_quest_id', 'user_id', name='uq_sq_completion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('side_quest_completions')
    op.drop_table('quest_completions')
    op.drop_table('proposal_votes')
    op.drop_table('competition_votes')
    op.drop_table('addon_quest_completions')
    op.drop_table('side_quests')
    op.drop_table('quest_proposals')
    op.drop_table('quest_instances')
    op.drop_table('addon_quests')
    op.drop_table('trades')
    op.drop_table('seasonal_points')
    op.drop_table('quest_templates')
    op.drop_table('guild_members')
    op.drop_table('guild_archives')
    op.drop_table('xp_transactions')
    op.drop_table('weekly_streak_log')
    op.drop_table('user_badges')
    op.drop_table('sessions')
    op.drop_table('sanctums')
    op.drop_table('point_transactions')
    op.drop_table('password_reset_tokens')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_table('guilds')
    op.drop_table('daily_trade_caps')
    op.drop_table('daily_streak_log')
    op.drop_table('users')
    op.drop_table('level_titles')
    op.drop_table('badges')
    # ### end Alembic commands ###
